/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestAccountRouteImport } from './routes/request-account'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BedsRouteImport } from './routes/beds'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccountRoute = RequestAccountRouteImport.update({
  id: '/request-account',
  path: '/request-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsRoute = BedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/beds': typeof BedsRoute
  '/billing': typeof BillingRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/request-account': typeof RequestAccountRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/beds': typeof BedsRoute
  '/billing': typeof BillingRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/request-account': typeof RequestAccountRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/beds': typeof BedsRoute
  '/billing': typeof BillingRoute
  '/doctors': typeof DoctorsRoute
  '/laboratory': typeof LaboratoryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/request-account': typeof RequestAccountRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/doctors'
    | '/laboratory'
    | '/login'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/records'
    | '/reports'
    | '/request-account'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/doctors'
    | '/laboratory'
    | '/login'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/records'
    | '/reports'
    | '/request-account'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/appointments'
    | '/beds'
    | '/billing'
    | '/doctors'
    | '/laboratory'
    | '/login'
    | '/notifications'
    | '/patients'
    | '/pharmacy'
    | '/records'
    | '/reports'
    | '/request-account'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BedsRoute: typeof BedsRoute
  BillingRoute: typeof BillingRoute
  DoctorsRoute: typeof DoctorsRoute
  LaboratoryRoute: typeof LaboratoryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientsRoute: typeof PatientsRoute
  PharmacyRoute: typeof PharmacyRoute
  RecordsRoute: typeof RecordsRoute
  ReportsRoute: typeof ReportsRoute
  RequestAccountRoute: typeof RequestAccountRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-account': {
      id: '/request-account'
      path: '/request-account'
      fullPath: '/request-account'
      preLoaderRoute: typeof RequestAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beds': {
      id: '/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof BedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  BedsRoute: BedsRoute,
  BillingRoute: BillingRoute,
  DoctorsRoute: DoctorsRoute,
  LaboratoryRoute: LaboratoryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PatientsRoute: PatientsRoute,
  PharmacyRoute: PharmacyRoute,
  RecordsRoute: RecordsRoute,
  ReportsRoute: ReportsRoute,
  RequestAccountRoute: RequestAccountRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
